### ISSUE TITLE
keyof is unknown with bundled tsserver (tide 20161205.2257)

### ISSUE THREAD

**Issue by asmundg** [ananthakumaran/tide#93]
I'm not 100% certain of how the toolchain works here, so sorry in advance if this is adressed to the wrong place. The typescript-tide flychecker appears to fail when using tide's bundled tsserver. The following compiles fine with tsc 2.1.4, but the checker fails with "Cannot find name 'keyof'":

```
interface Foo {
    a: string;
}

export function foo(foo: keyof Foo) {
    return foo;
}

foo("a");
//foo("b");
```

**Comment by ananthakumaran** [comment]
can we close this?

**Comment by asmundg** [comment]
I believe so. Thanks!
